### PR TITLE
Filtering StackExchange

### PR DESCRIPTION
**Pull request by hoonose**
Currently, everything from StackExchange is being posted. This should result in it being filtered down to just the "good" posts.

### CODE REVIEW

**Review by geomblog — CHANGES_REQUESTED** [review]
I don't see the actual ilya.jpeg file?

**Comment by hoonose** [comment]
The ilya.jpeg file is associated with an unrelated edit, this pull request is to do solely with StackExchange posts. I have staged commits for the other edit only in my own repo.

That said, since you asked, here is a direct link to the image (which is the one he suggested, and I edited down to an appropriate size): https://github.com/hoonose/abhatt.github.io/blob/6ccd378bbf9daeaed096bc8e2dda573a3a78dc8a/images/ilya.jpeg

**Comment by hoonose** [comment]
And to further clarify regarding the other change: due to the structure of this project, for the addition of a blog, it requires changes to both repositories: a change in toc.ini to add it to the listing in this repo, and the addition of a picture in the other repo (https://github.com/hoonose/abhatt.github.io/tree/master/images). 

I've made these commits on my local repo as https://github.com/hoonose/aggregator/commit/d3766dfa9f018146c94b8966bb3d9e8df10d18a6 and https://github.com/hoonose/abhatt.github.io/commit/6ccd378bbf9daeaed096bc8e2dda573a3a78dc8a respectively.

**Comment by hoonose** [comment]
OK, I apparently don't know how github works. This pull request is now for 2 changes. The first one is the Filtering StackExchange one. The second change is to add Ilya's blog, upon request.

Either way, to answer your question: due to the structure of the project, the .jpeg file is in a commit to the other repository (where the images are stored). It can be reviewed here: https://github.com/abhatt/abhatt.github.io/pull/1.

**Pull request merged**
